# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainrpc/chainkit.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("chainrpc/chainkit.proto", :syntax => :proto3) do
    add_message "chainrpc.GetBlockRequest" do
      optional :block_hash, :bytes, 1
    end
    add_message "chainrpc.GetBlockResponse" do
      optional :raw_block, :bytes, 1
    end
    add_message "chainrpc.GetBestBlockRequest" do
    end
    add_message "chainrpc.GetBestBlockResponse" do
      optional :block_hash, :bytes, 1
      optional :block_height, :int32, 2
    end
    add_message "chainrpc.GetBlockHashRequest" do
      optional :block_height, :int64, 1
    end
    add_message "chainrpc.GetBlockHashResponse" do
      optional :block_hash, :bytes, 1
    end
  end
end

module Chainrpc
  GetBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chainrpc.GetBlockRequest").msgclass
  GetBlockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chainrpc.GetBlockResponse").msgclass
  GetBestBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chainrpc.GetBestBlockRequest").msgclass
  GetBestBlockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chainrpc.GetBestBlockResponse").msgclass
  GetBlockHashRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chainrpc.GetBlockHashRequest").msgclass
  GetBlockHashResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chainrpc.GetBlockHashResponse").msgclass
end
